name: build

env:
  # Contants
  PREFIX: GifSyncAnimator
  CMAKE_BUILD_DIR: __build
  JUCE_GIT_USE_TAGNAME: 7.0.9
  # Variables
  artifact_suffix: ""

on:
  workflow_call:
    inputs:
      build-platform:
        required: false
        type: string
        default: "Windows"
      build-configuration:
        required: true
        type: string
      version:
        required: false
        type: string
      append-sha-to-artifact:
        required: false
        type: boolean

  workflow_dispatch:
    inputs:
      build-platform:
        description: "Target Platform"
        required: false
        type: string
        default: "Windows, Mac"
      build-configuration:
        description: "Build configuration"
        required: true
        type: choice
        options:
          - Debug
          - Release
      version:
        description: "Version. Semantical versioning is recommended"
        required: false
        type: string
        default: ""
      append-sha-to-artifact:
        description: "Append SHA to artifact name"
        required: false
        type: boolean
        default: false
jobs:
  #--------------------------------------------------------------
  # Windows
  #--------------------------------------------------------------
  windows-build:
    if: contains(inputs.build-platform, 'Windows')
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout JUCE Submodule
      shell: cmd
      run: |
        cd libs\JUCE
        git checkout ${{ env.JUCE_GIT_USE_TAGNAME }}

    - name: CMake Create Buildsystem
      shell: cmd
      run: cmake -B ${{ env.CMAKE_BUILD_DIR }} -A x64 -G "Visual Studio 17 2022" ${{ github.workspace }}

    - name: CMake Build
      shell: cmd
      run: cmake --build ${{ env.CMAKE_BUILD_DIR }} --config ${{ inputs.build-configuration }}

    - name: Setup Artifact Suffix
      shell: cmd
      run: |
        set ARTIFACT_SUFFIX=

        if not "${{ inputs.version }}" == "" (
            set ARTIFACT_SUFFIX=-v${{ inputs.version }}
        )

        if "${{ inputs.append-sha-to-artifact }}" == "true" (
            set ARTIFACT_SUFFIX=%ARTIFACT_SUFFIX%-${{ github.sha }}
        )

        if not "%ARTIFACT_SUFFIX%" == "" (
            echo artifact_suffix=%ARTIFACT_SUFFIX% >> %GITHUB_ENV%
        )

    - name: Copying Assets to VST build artefact
      shell: cmd
      run: |
        xcopy /E ${{ env.CMAKE_BUILD_DIR }}\${{ env.PREFIX }}_assets\* ${{ env.CMAKE_BUILD_DIR }}\${{ env.PREFIX }}_artefacts\${{ inputs.build-configuration }}\VST3\

    - name: Artifact Windows VST3
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PREFIX }}-Windows-${{ inputs.build-configuration }}-VST3${{ env.artifact_suffix }}
        path: ${{ env.CMAKE_BUILD_DIR }}/${{ env.PREFIX }}_artefacts/${{ inputs.build-configuration }}/VST3/*

  #--------------------------------------------------------------
  # Mac
  #--------------------------------------------------------------
  mac-build:
    if: contains(inputs.build-platform, 'Mac')
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout JUCE Submodule
      shell: bash
      run: |
        cd libs/JUCE
        git checkout ${{ env.JUCE_GIT_USE_TAGNAME }}

    - name: CMake Create Buildsystem
      shell: bash
      run: cmake -B ${{ env.CMAKE_BUILD_DIR }} -D CMAKE_OSX_ARCHITECTURES="arm64;x86_64" -G Xcode ${{ github.workspace }}

    - name: CMake Build
      shell: bash
      run: cmake --build ${{ env.CMAKE_BUILD_DIR }} --config ${{ inputs.build-configuration }}

    - name: Setup Artifact Suffix
      shell: bash
      run: |
        ARTIFACT_SUFFIX=

        if [ "${{ inputs.version }}" != "" ]; then
            ARTIFACT_SUFFIX=-v${{ inputs.version }}
        fi

        if [ "${{ inputs.append-sha-to-artifact }}" = "true" ]; then
            ARTIFACT_SUFFIX="${ARTIFACT_SUFFIX}-${{ github.sha }}"
        fi

        if [ "$ARTIFACT_SUFFIX" != "" ]; then
            echo "artifact_suffix=$ARTIFACT_SUFFIX" >> $GITHUB_ENV
        fi

    - name: Copying Assets to AU build artefact
      shell: bash
      run: |
        cp -r ${{ env.CMAKE_BUILD_DIR }}/${{ env.PREFIX }}_assets/* ${{ env.CMAKE_BUILD_DIR }}/${{ env.PREFIX }}_artefacts/${{ inputs.build-configuration }}/AU/

    - name: Copying Assets to VST build artefact
      shell: bash
      run: |
        cp -r ${{ env.CMAKE_BUILD_DIR }}/${{ env.PREFIX }}_assets/* ${{ env.CMAKE_BUILD_DIR }}/${{ env.PREFIX }}_artefacts/${{ inputs.build-configuration }}/VST3/

    - name: Artifact Mac AU
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PREFIX }}-Mac-${{ inputs.build-configuration }}-AU${{ env.artifact_suffix }}
        path: ${{ env.CMAKE_BUILD_DIR }}/${{ env.PREFIX }}_artefacts/${{ inputs.build-configuration }}/AU/*

    - name: Artifact Mac VST3
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PREFIX }}-Mac-${{ inputs.build-configuration }}-VST3${{ env.artifact_suffix }}
        path: ${{ env.CMAKE_BUILD_DIR }}/${{ env.PREFIX }}_artefacts/${{ inputs.build-configuration }}/VST3/*
